/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pbo13_24060124130061_nomor_4;

import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class NewJFrame extends javax.swing.JFrame {
    DefaultListModel<String> model = new DefaultListModel<>();

List<String> dataList = new ArrayList<>();
Set<String> dataSet = new HashSet<>();
Map<Integer, String> dataMap = new HashMap<>();

int keyMap = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    public NewJFrame() {
        initComponents();
        jList1.setModel(model);

        model.addElement("buku");
        model.addElement("meja");
        model.addElement("kursi");
        model.addElement("tas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SavetoList = new javax.swing.JButton();
        InserttoList = new javax.swing.JButton();
        SavetoSet = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SavetoMap = new javax.swing.JButton();
        InsertToMap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ClearAll = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SavetoList.setText("Save to List ->");
        SavetoList.addActionListener(this::SavetoListActionPerformed);

        InserttoList.setText("<- Insert to List");
        InserttoList.addActionListener(this::InserttoListActionPerformed);

        SavetoSet.setText("Save to Set ->");
        SavetoSet.addActionListener(this::SavetoSetActionPerformed);

        jButton4.setText("<- Insert to Set");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        SavetoMap.setText("Save to Map ->");
        SavetoMap.addActionListener(this::SavetoMapActionPerformed);

        InsertToMap.setText("<-Insert to Map");
        InsertToMap.addActionListener(this::InsertToMapActionPerformed);

        jLabel1.setText("Item Name");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        ClearAll.setText("Clear All");
        ClearAll.addActionListener(this::ClearAllActionPerformed);

        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);

        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SavetoMap)
                    .addComponent(InsertToMap)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavetoList)
                            .addComponent(InserttoList)
                            .addComponent(SavetoSet)
                            .addComponent(jButton4)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ClearAll)
                .addGap(45, 45, 45)
                .addComponent(Add)
                .addGap(8, 8, 8)
                .addComponent(Update)
                .addGap(8, 8, 8)
                .addComponent(Delete))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SavetoList)
                        .addGap(15, 15, 15)
                        .addComponent(InserttoList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SavetoSet)
                        .addGap(12, 12, 12)
                        .addComponent(jButton4)
                        .addGap(16, 16, 16)
                        .addComponent(SavetoMap)
                        .addGap(17, 17, 17)
                        .addComponent(InsertToMap)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearAll)
                    .addComponent(Add)
                    .addComponent(Update)
                    .addComponent(Delete)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void InserttoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserttoListActionPerformed
            model.clear();

    for(String item : dataList) {
        model.addElement(item);
    }

    }//GEN-LAST:event_InserttoListActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
        model.clear();
    }//GEN-LAST:event_ClearAllActionPerformed

    private void SavetoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavetoListActionPerformed
           dataList.clear();

    for(int i = 0; i < model.size(); i++) {
        dataList.add(model.getElementAt(i));
    }

    JOptionPane.showMessageDialog(this,
            "Data List tersimpan = " + dataList.size());
    }//GEN-LAST:event_SavetoListActionPerformed

    private void SavetoSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavetoSetActionPerformed
           dataSet.clear();

    for(int i = 0; i < model.size(); i++) {
        dataSet.add(model.getElementAt(i));
    }

    JOptionPane.showMessageDialog(this,
            "Data Set tersimpan = " + dataSet.size());
    }//GEN-LAST:event_SavetoSetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            model.clear();

    for(String item : dataSet) {
        model.addElement(item);
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void SavetoMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavetoMapActionPerformed
            dataMap.clear();

    keyMap = 0;

    for(int i = 0; i < model.size(); i++) {

        dataMap.put(keyMap, model.getElementAt(i));

        keyMap++;
    }

    JOptionPane.showMessageDialog(this,
            "Data Map tersimpan = " + dataMap.size());


    }//GEN-LAST:event_SavetoMapActionPerformed

    private void InsertToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertToMapActionPerformed
            model.clear();

    for(String item : dataMap.values()) {
        model.addElement(item);
    }

    }//GEN-LAST:event_InsertToMapActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        
    String item = jTextField1.getText();

    if(!item.isEmpty()) {

        model.addElement(item);

        jTextField1.setText("");
    }


    }//GEN-LAST:event_AddActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
            int index = jList1.getSelectedIndex();

    if(index != -1) {

        model.set(index, jTextField1.getText());

    }

    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
           int index = jList1.getSelectedIndex();

    if(index != -1) {

        model.remove(index);

    }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton Delete;
    private javax.swing.JButton InsertToMap;
    private javax.swing.JButton InserttoList;
    private javax.swing.JButton SavetoList;
    private javax.swing.JButton SavetoMap;
    private javax.swing.JButton SavetoSet;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
